---
- name: Start Apache
  hosts: ansibleclient

  tasks:
    - name: Apache installation
      apt: name=apache2 state=present

    - name: Apache configuration
      copy: content="This is my automated Webserver\n" dest=/var/www/html/index.html 
        
    - name: 
      lineinfile: path=/etc/apache2/ports.conf state=present regexp='^Listen 80' line='Listen 81' backrefs=yes
      notify:
        - restart apache
     
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
       
  

